#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Relevant SNMP OIDs:
#.1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4.9.0 = "    5 Secs (  5.8548%)   60 Secs (  7.2980%)  300 Secs (  7.7743%)"
#.1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4.10.0 = Gauge32: 7
#.1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4.11.0 = Gauge32: 17
#.1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4.12.0 = Gauge32: 18
#
import re

# Default values for parameters that can be overriden.
dell_n2000_cpu_default_levels = (80, 90)

# Inventory of dell power connect CPU details.
def inventory_dell_n2000_cpu(checkname, info):
    enabled = '1'
#    print info
    if info:
	t1 = re.sub(r".*\(\s+(\d.*)%\).+\(\s+(\d.*)%\).+\(\s+(\d.*)%\).*",  r'\1 \2 \3', str(info[0]))
        onesecondperc, oneminuteperc, fiveminutesperc = re.split(" ", str(t1), 3)
	onesecondperc = int(round(float(onesecondperc),0))
        if enabled == '1' and onesecondperc != '' and int(onesecondperc) >= 0:
#            print "return\n"
            return [ (None, 'dell_n2000_cpu_default_levels') ]

# Check of dell power connect CPU details.
def check_dell_n2000_cpu(item, params, info):
    enabled = 1
    try:
	t1 = re.sub(r".*\(\s+(\d.*)%\).+\(\s+(\d.*)%\).+\(\s+(\d.*)%\).*",  r'\1 \2 \3', str(info[0]))
        onesecondperc, oneminuteperc, fiveminutesperc = re.split(" ", str(t1), 3)
	onesecondperc = int(round(float(onesecondperc),0))
	oneminuteperc = int(round(float(oneminuteperc),0))
	fiveminutesperc = int(round(float(fiveminutesperc),0))
    except ValueError:
        raise MKCounterWrapped("Ignoring empty data from SNMP agent")
    if int(enabled) == 1:
        cpu_util = saveint(onesecondperc)
        if cpu_util >= 0 <= 100:
            status = 0
            output = ''
            if cpu_util >= params[1]:
                status = 2
                output = ' (Above %d%%)' % params[1]
            elif cpu_util >= params[0]:
                status = 1
                output = ' (Above %d%%)' % params[0]

            # Darn. It again happend. Someone mixed up load and utilization.
            # We do *not* rename the performance variables here, in order not
            # to mix up existing RRDs...
            return (status, 'CPU utilization is %d%% %s' % (cpu_util, output),
                   [('load', '%d%%' % cpu_util, params[0], params[1], 0, 100),
                    ('loadavg-60s', '%d%%' % saveint(oneminuteperc), params[0], params[1], 0, 100),
                    ('loadavg-5m', '%d%%' % saveint(fiveminutesperc), params[0], params[1], 0, 100),
                   ])

    return (3, "Invalid  information in SNMP data")

check_info["dell_n2000_cpu"] = {
    'check_function':          check_dell_n2000_cpu,
    'inventory_function':      inventory_dell_n2000_cpu,
    'service_description':     'CPU utilization',
    'has_perfdata':            True,
#    'snmp_info':               ('.1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4', ['10', '11', '12']),
    'snmp_info':               ('.1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4', ['9']),
    'snmp_scan_function':      \
     lambda oid: ".1.3.6.1.4.1.674.10895" in oid(".1.3.6.1.2.1.1.2.0")
}
